# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55209e9c11e836c62de98f30b27445f2cb92567b018c388931b21c47998f80967c250d73e37f7d610c16bc42be9c4c29859a9669fbe1967d08d8c05c3b1af72b

test:
  secret_key_base: 10ba3b0427612c6821d0fb97f179db740bac6d5e5a58827a6a45e5a4a4073686081bf5447c4a47d98239a8aa3d9cfd6993508975dacfda447ff905308b3be32b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
